import type { Metadata } from "next";
import "@/app/globals.css";

import NextUIProviderWrapper from "@/app/[locale]/provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: { locale: string };
}

const RootLayout = ({ children, params: { locale } }: RootLayoutProps) => {
	return (
		<html lang={locale}>
			<body>
				<NextUIProviderWrapper locale={locale}>{children}</NextUIProviderWrapper>
			</body>
		</html>
	);
};

export default RootLayout;
